---
libreoffice_version: "26.2.4"
libreoffice_temp_dir: "C:\\install\\libreoffice"
libreoffice_url: "https://download.documentfoundation.org/libreoffice/stable/26.2.4/win/x86_64/LibreOffice_26.2.4_Win_x86-64.msi"
