---
- name: Remove local console login for sshadmin
  hosts: windows
  gather_facts: no
  serial: 1

  vars:
    ssh_admin_user: sshadmin

  tasks:

    - name: Deny local console logon for sshadmin
      ansible.windows.win_user_right:
        name: SeDenyInteractiveLogonRight
        users:
          - "{{ ssh_admin_user }}"
        action: remove

