---
- name: Update Windows computers
  hosts: windows
  gather_facts: no

  roles:
    - role: idle_logoff
    - role: users_logged_in
    - role: windows_update
      when: not users_logged_in
    - role: reboot_if_no_users
      when: not users_logged_in 
