---
- name: Create installer directory
  ansible.builtin.file:
    path: "/mnt/c/files/{{ name }}"
    state: directory
    mode: "0755"

- name: Download installer
  ansible.builtin.get_url:
    url: "{{ source_url }}"
    dest: "/mnt/c/files/{{ name }}/installer"
    mode: "0644"
    force: false
